### PR TITLE
Handling Rational

### PR DESCRIPTION
**Pull request by cantin**
Base on https://github.com/zdavatz/spreadsheet/pull/33

I added a Rational support and test for it.

### CODE REVIEW

**Comment by zdavatz** [comment]
your test does not pass on Ruby 1.8.7. Did you check that as well?

**Comment by zdavatz** [comment]
the error I get for Ruby 1.8.7 is: 

```
  1) Error:
test_rational(Spreadsheet::TestIntegration):
NoMethodError: undefined method `gcd' for 10.12:Float
    /home/zeno/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/rational.rb:78:in `reduce'
    /home/zeno/.rvm/rubies/ruby-1.8.7-p374/lib/ruby/1.8/rational.rb:35:in `Rational'
    ./test/integration.rb:1148:in `test_rational'

85 tests, 1098 assertions, 0 failures, 1 errors
```

**Comment by cantin** [comment]
Sorry about that. Should be fixed now.

**Comment by zdavatz** [comment]
Thanks! Version 1.0.2 is out. Please test.

**Pull request merged**
