### PR TITLE
request to include freeze functionality that I created

### PR DESCRIPTION
**Pull request by poldz**
request to include freeze functionality that I created

### CODE REVIEW

**Comment by zdavatz** [comment]
Did you create a test for this feature?

**Comment by poldz** [comment]
Nope :) , I hope someone could help do it

**Comment by zdavatz** [comment]
Can you try your self? There are plenty of tests already.

**Comment by poldz** [comment]
ok, I will try to find time  :+1:

**Comment by zdavatz** [comment]
that would be great!

**Comment by poldz** [comment]
Hi zdavatz 

I created a test @worksheet level

Regards,
bong

**Comment by zdavatz** [comment]
thank you. Version 1.0.7 is out.

**Comment by poldz** [comment]
your welcome

On Wed, Sep 23, 2015 at 5:40 PM, Zeno R.R. Davatz <notifications@github.com>
wrote:

> thank you. Version 1.0.7 is out.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zdavatz/spreadsheet/pull/149#issuecomment-142546947>.
>



-- 
Bong

**Comment by QuotableWater7** [comment]
@poldz could you please explain how this works?  is this the feature I would use to make sure the top row of my spreadsheet is always visible?

**Pull request merged**
