### PR TITLE
Test delete_row.

### PR DESCRIPTION
**Pull request by runephilosof**
This test is failing for me.

### CODE REVIEW

**Comment by zdavatz** [comment]
So what did you do? Did you fix the test or the code?

**Comment by zdavatz** [comment]
Also your commit fails all Travis builds, that are green at the moment.

**Comment by runephilosof** [comment]
Sorry. I should have posted this as an issue.
I have created a new test to demonstrate my problem.
When I try to delete the row from the added file, nothing happens.

I can close this one and create an issue instead if you prefer.

**Comment by zdavatz** [comment]
Yes please. Create an issue.

**Comment by zdavatz** [comment]
what I need from you is sample script that is publicly available at gist.github.com together with a sample file so I can test everything. What Ruby Version are you using?

**Pull request closed without merging**
