### PR TITLE
Also ignore locale indicators in number formats containing a letter

### PR DESCRIPTION
**Pull request by kinkou**
Some locale indicators may contain a letter, like '[$-F800]'

### CODE REVIEW

**Comment by zdavatz** [comment]
Please make sure that all the tests pass.

**Comment by zdavatz** [comment]
are you sending me a new Pull request?

**Comment by kinkou** [comment]
No, sorry. Too much trouble adjusting it for 1.8.7, jruby, etc. Besides, this locale marker seems to be either rare or invalid. I'm fine with a workaround in my 'local' code. Whoever else runs into this problem will find a solution here.

**Comment by zdavatz** [comment]
Ok. Thank you for your effort.

**Pull request closed without merging**
