### PR TITLE
fixed unit test errors caused by frozen string literal

### PR DESCRIPTION
**Pull request by taichi-ishitani**
Hi,

I fixed unit test errors caused by frozen string literal.
af6206e

To test above changes on CI regression, I also changed files below too:

* Gemfile
    * I forked and changed `ruby-ole` gem for frozen string literal support.
        * I open the PR for these fix.
    * When run unit tests with frozen string literal, use my forked `ruby-ole` gem instead of the original gem.
* Gemfile.lock
    * Removed this file because the previous Rake does not support frozen string literal
* .travis.yml
    * added newer rubies (2.3.8, 2.4.5, 2.5.3 and 2.6.1)
    * enable `--enable-frozen-string-literal` when ruby version is >= 2.4
        * ruby 2.3 also supports `--enable-frozen-string-literal` option but it seems that standard libraries does not support the feature enough.
       * Therefore, I don't combination of ruby 2.3 and  `--enable-frozen-string-literal` option to CI regression.

If you don't want to introduce changes of Gemfile, Gemfile.lock and .travis.yml to master repository, please ignore commits 75caf13 and ec10f8b.

### CODE REVIEW

**Comment by zdavatz** [comment]
Aligatoo!

**Comment by taichi-ishitani** [comment]
Hi @zdavatz ,

Thank you for merging my PR !
BTW, there're something I have to tell you:

1.  I disabled e-mail notification from Travis CI temporally. If you want to get e-mail notification, you need to edit .travis.yml and revert lines bellow.
    - https://github.com/zdavatz/spreadsheet/blob/077190946d24d7779c00fa0a3a890704d9a39fbc/.travis.yml#L44
2. You should edit Gemfile and revert `ruby-ole` dependency when my PR (aquasync/ruby-ole#24) is merged and the `ruby-ole` gem including my PR is released. In addition you also need to edit .travis.yml and delete `USE_LATEST_RUBY_OLE=yes` environment variable definitions.
    - https://github.com/zdavatz/spreadsheet/blob/077190946d24d7779c00fa0a3a890704d9a39fbc/Gemfile#L3
    - https://github.com/zdavatz/spreadsheet/blob/077190946d24d7779c00fa0a3a890704d9a39fbc/.travis.yml#L31

**Comment by zdavatz** [comment]
1. I do not care about the Email notifications.
2. Can you please send me a pull request for this? Why does this need a change again?

**Comment by taichi-ishitani** [comment]
> 2. Can you please send me a pull request for this, once your PR for Ruby-Ole is merged?
Sure ! Is linked-in message OK?

**Comment by taichi-ishitani** [comment]
> 2. Can you please send me a pull request for this, once your PR for Ruby-Ole is merged?

OK. I will send PR when my PR for ruby-ole is merged.

**Comment by zdavatz** [comment]
Great! Thank you!

**Pull request merged**
